import '../borrower_home_screen/widgets/applyforloan_item_widget.dart';import '../borrower_home_screen/widgets/totalloansframe1_item_widget.dart';import 'controller/borrower_home_controller.dart';import 'models/applyforloan_item_model.dart';import 'models/totalloansframe1_item_model.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/presentation/borrower_home_empty_page/borrower_home_empty_page.dart';import 'package:loan_link/presentation/loans_empty_page/loans_empty_page.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:loan_link/widgets/app_bar/appbar_subtitle_two.dart';import 'package:loan_link/widgets/app_bar/appbar_trailing_image.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_bottom_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';class BorrowerHomeScreen extends GetWidget<BorrowerHomeController> {const BorrowerHomeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 72.v), CustomElevatedButton(height: 18.v, width: 160.h, text: "msg_loan_limit_n50_000".tr, margin: EdgeInsets.only(left: 20.h), rightIcon: Container(margin: EdgeInsets.only(left: 4.h), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleSmallBold, onPressed: () {onTapLoanLimitN50000();}, alignment: Alignment.centerLeft), SizedBox(height: 9.v), _buildTotalLoansFrame(), SizedBox(height: 32.v), _buildTransactionCard(), SizedBox(height: 49.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_quick_actions".tr, style: CustomTextStyles.titleMediumMedium))), SizedBox(height: 18.v), _buildApplyForLoan()])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse1103, margin: EdgeInsets.only(left: 20.h)), title: AppbarSubtitleTwo(text: "lbl_hi_mcclive".tr, margin: EdgeInsets.only(left: 3.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconsBlueGray900, margin: EdgeInsets.symmetric(horizontal: 20.h))]); } 
/// Section Widget
Widget _buildTotalLoansFrame() { return SizedBox(height: 86.v, child: Obx(() => ListView.separated(padding: EdgeInsets.symmetric(horizontal: 20.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.borrowerHomeModelObj.value.totalloansframe1ItemList.value.length, itemBuilder: (context, index) {Totalloansframe1ItemModel model = controller.borrowerHomeModelObj.value.totalloansframe1ItemList.value[index]; return Totalloansframe1ItemWidget(model);}))); } 
/// Section Widget
Widget _buildTransactionCard() { return Container(margin: EdgeInsets.symmetric(horizontal: 20.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 16.v), decoration: AppDecoration.gradientErrorContainerToBlueGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_latest_transactions".tr, style: CustomTextStyles.titleMediumPrimaryContainerMedium), Text("lbl_see_more".tr, style: CustomTextStyles.titleSmallDeeppurpleA200)]), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 8.h), child: _buildFrame(userImage: ImageConstant.imgIconsGreenA70024x24, userName: "lbl_samuel_mcclive".tr, date: "lbl_17_03_2023".tr, time: "lbl_6_45pm".tr, userScore: "lbl_40_000".tr)), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 8.h), child: _buildFrame(userImage: ImageConstant.imgIconsOnprimarycontainer24x24, userName: "lbl_samuel_mcclive".tr, date: "lbl_17_03_2023".tr, time: "lbl_6_45pm".tr, userScore: "lbl_100_000".tr)), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildApplyForLoan() { return SizedBox(height: 92.v, child: Obx(() => ListView.separated(padding: EdgeInsets.symmetric(horizontal: 20.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 24.h);}, itemCount: controller.borrowerHomeModelObj.value.applyforloanItemList.value.length, itemBuilder: (context, index) {ApplyforloanItemModel model = controller.borrowerHomeModelObj.value.applyforloanItemList.value[index]; return ApplyforloanItemWidget(model, onTapApplyForLoan: () {onTapApplyForLoan();});}))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildFrame({required String userImage, required String userName, required String date, required String time, required String userScore, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 7.v)), Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(userName, style: CustomTextStyles.bodyMediumPrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer)), SizedBox(height: 4.v), SizedBox(width: 123.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text(date, style: CustomTextStyles.bodySmallGothicA1Gray200.copyWith(color: appTheme.gray200))), Text(time, style: CustomTextStyles.bodySmallGothicA1Gray200.copyWith(color: appTheme.gray200))]))])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: Text(userScore, style: CustomTextStyles.titleMediumPrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer)))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.borrowerHomeEmptyPage; case BottomBarEnum.Loans: return AppRoutes.loansEmptyPage; case BottomBarEnum.Notifications: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.borrowerHomeEmptyPage: return BorrowerHomeEmptyPage(); case AppRoutes.loansEmptyPage: return LoansEmptyPage(); default: return DefaultWidget();} } 
/// Navigates to the loanRequestOneScreen when the action is triggered.
onTapApplyForLoan() { Get.toNamed(AppRoutes.loanRequestOneScreen); } 
/// Navigates to the loanLimitInfoScreen when the action is triggered.
onTapLoanLimitN50000() { Get.toNamed(AppRoutes.loanLimitInfoScreen, ); } 
 }
