import 'controller/log_in_controller.dart';import 'package:country_pickers/country.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/core/utils/validation_functions.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';import 'package:loan_link/widgets/custom_icon_button.dart';import 'package:loan_link/widgets/custom_phone_number.dart';import 'package:loan_link/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LogInScreen extends GetWidget<LogInController> {LogInScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_welcome_back".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_glad_to_see_you".tr, style: CustomTextStyles.bodyMediumOnPrimary)), SizedBox(height: 64.v), _buildFrame(), SizedBox(height: 23.v), _buildFrame1(), SizedBox(height: 36.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 23.h), child: Text("msg_forgot_password".tr, style: CustomTextStyles.titleSmallPrimary_1))), SizedBox(height: 59.v), _buildFrame2(), SizedBox(height: 20.v), GestureDetector(onTap: () {onTapTxtNewtoloanlink();}, child: Padding(padding: EdgeInsets.only(left: 23.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_new_to_loanlink2".tr, style: CustomTextStyles.bodyLargeGray800_1), TextSpan(text: "lbl_create_account".tr, style: CustomTextStyles.titleMediumPrimary)]), textAlign: TextAlign.left))), SizedBox(height: 5.v)]))))); } 
/// Section Widget
Widget _buildFrame() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_phone_number".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), Obx(() => CustomPhoneNumber(country: controller.selectedCountry.value, controller: controller.phoneNumberController, onTap: (Country country) {controller.selectedCountry.value = country;}))]))); } 
/// Section Widget
Widget _buildFrame1() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), Obx(() => CustomTextFormField(controller: controller.passwordController, hintText: "lbl_enter_password".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(12.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgIconsGray60001, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 48.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value, contentPadding: EdgeInsets.only(left: 8.h, top: 15.v, bottom: 15.v)))]))); } 
/// Section Widget
Widget _buildFrame2() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_log_in".tr, onPressed: () {onTapLogIn();})), Padding(padding: EdgeInsets.only(left: 16.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgFingerprint)))]))); } 
/// Navigates to the roleSelectionOneScreen when the action is triggered.
onTapLogIn() { Get.toNamed(AppRoutes.roleSelectionOneScreen, ); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapTxtNewtoloanlink() { Get.toNamed(AppRoutes.signUpScreen, ); } 
 }
