import 'controller/personalized_goals_controller.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_image.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_drop_down.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';class PersonalizedGoalsScreen extends GetWidget<PersonalizedGoalsController> {const PersonalizedGoalsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 24.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_thumbs_up".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 3.v), Container(width: 379.h, margin: EdgeInsets.only(right: 10.h), child: Text("msg_get_personalized".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimary.copyWith(height: 1.43))), SizedBox(height: 23.v), CustomElevatedButton(height: 24.v, width: 85.h, text: "lbl_step_3_0f_4".tr, buttonStyle: CustomButtonStyles.fillDeepPurple, buttonTextStyle: CustomTextStyles.labelLargeBluegray900, alignment: Alignment.centerLeft), SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_funding_goals".tr, style: CustomTextStyles.titleMediumMedium18)), SizedBox(height: 24.v), _buildFrame(), SizedBox(height: 24.v), _buildFrame1(), SizedBox(height: 25.v), _buildFrame2(), SizedBox(height: 40.v), CustomElevatedButton(text: "lbl_proceed".tr, onPressed: () {onTapProceed();}), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, right: 386.h), onTap: () {onTapArrowLeft();})); } 
/// Section Widget
Widget _buildFrame() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_what_sector_s_are".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "msg_select_sector_s".tr, items: controller.personalizedGoalsModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildFrame1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_what_business_type_s".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "msg_select_business".tr, items: controller.personalizedGoalsModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);})]); } 
/// Section Widget
Widget _buildFrame2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_what_loan_range".tr, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "msg_select_loan_range".tr, items: controller.personalizedGoalsModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);})]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the securityOneScreen when the action is triggered.
onTapProceed() { Get.toNamed(AppRoutes.securityOneScreen, ); } 
 }
