import 'controller/loan_details_controller.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_image.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';class LoanDetailsScreen extends GetWidget<LoanDetailsController> {const LoanDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 55.v), _buildThirtyFour(), SizedBox(height: 13.v), CustomElevatedButton(height: 20.v, width: 70.h, text: "lbl_engineering".tr, margin: EdgeInsets.only(left: 20.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: theme.textTheme.labelSmall!, alignment: Alignment.centerLeft), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_tyson_s_story".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 9.v), Align(alignment: Alignment.centerLeft, child: Container(width: 376.h, margin: EdgeInsets.only(left: 20.h, right: 33.h), child: Text("msg_tyson_is_a_21_year_old".tr, maxLines: 12, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.43)))), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_loan_details".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 12.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(loanLength: "lbl_loan_amount".tr, duration: "lbl_ngn50_000".tr)), SizedBox(height: 18.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(loanLength: "lbl_loan_length".tr, duration: "lbl_3_months".tr)), SizedBox(height: 19.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(loanLength: "msg_repayment_schedule".tr, duration: "lbl_monthly".tr)), SizedBox(height: 19.v), Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: _buildFrame(loanLength: "lbl_applied_date".tr, duration: "msg_10th_september".tr)), SizedBox(height: 18.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(loanLength: "lbl_due_date".tr, duration: "msg_10th_december_2023".tr))])))), bottomNavigationBar: _buildFund())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, right: 386.h), onTap: () {onTapArrowLeft();})); } 
/// Section Widget
Widget _buildThirtyFour() { return SizedBox(height: 203.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgRectangle20066203x430, height: 203.v, width: 430.h, alignment: Alignment.center), CustomElevatedButton(height: 20.v, width: 60.h, text: "lbl_ogun".tr, margin: EdgeInsets.only(left: 24.h, bottom: 16.v), leftIcon: Container(margin: EdgeInsets.only(right: 2.h), child: CustomImageView(imagePath: ImageConstant.imgIconsBlueGray9008x8, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryContainerTL10, buttonTextStyle: theme.textTheme.labelMedium!, alignment: Alignment.bottomLeft)])); } 
/// Section Widget
Widget _buildFund() { return CustomElevatedButton(height: 48.v, text: "lbl_fund".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 43.v), onPressed: () {onTapFund();}); } 
/// Common widget
Widget _buildFrame({required String loanLength, required String duration, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(loanLength, style: theme.textTheme.bodyLarge!.copyWith(color: appTheme.gray700))), Text(duration, style: CustomTextStyles.titleMediumGray700.copyWith(color: appTheme.gray700))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the fundBorrowerScreen when the action is triggered.
onTapFund() { Get.toNamed(AppRoutes.fundBorrowerScreen, ); } 
 }
