import '../loans_screen/widgets/loandetails1_item_widget.dart';import 'controller/loans_controller.dart';import 'models/loandetails1_item_model.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/presentation/borrower_home_empty_page/borrower_home_empty_page.dart';import 'package:loan_link/presentation/loans_empty_page/loans_empty_page.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_image.dart';import 'package:loan_link/widgets/app_bar/appbar_subtitle_one.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_bottom_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';import 'package:loan_link/presentation/loanlinkers_permission_dialog/loanlinkers_permission_dialog.dart';import 'package:loan_link/presentation/loanlinkers_permission_dialog/controller/loanlinkers_permission_controller.dart';class LoansScreen extends GetWidget<LoansController> {const LoansScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 96.v), SizedBox(height: 165.adaptSize, width: 165.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 165.adaptSize, width: 165.adaptSize, child: CircularProgressIndicator(value: 0.5, backgroundColor: appTheme.gray200, color: appTheme.greenA700))), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Text("lbl_100_000_ngn".tr, style: CustomTextStyles.titleMediumBold18), SizedBox(height: 6.v), Text("lbl_total_loan".tr, style: CustomTextStyles.titleSmallOnError)])))])), SizedBox(height: 24.v), _buildFrame(), SizedBox(height: 24.v), CustomElevatedButton(width: 117.h, text: "lbl_repay_loan".tr, onPressed: () {onTapRepayLoan();}), SizedBox(height: 24.v), _buildLoanHistory(), SizedBox(height: 8.v), _buildLoanDetails()]))), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 94.v, leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, top: 1.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleOne(text: "lbl_loans".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildFrame() { return Container(margin: EdgeInsets.symmetric(horizontal: 20.h), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 8.v), decoration: AppDecoration.outlineGray40001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 12.v, width: 35.h, decoration: BoxDecoration(color: appTheme.greenA700, borderRadius: BorderRadius.circular(6.h))), SizedBox(height: 10.v), Text("lbl_ngn80_000".tr, style: theme.textTheme.titleMedium), SizedBox(height: 3.v), Text("lbl_paid".tr, style: CustomTextStyles.titleSmallGray60001)])), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 12.v, width: 35.h, decoration: BoxDecoration(color: appTheme.gray200, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.blueGray10001, width: 1.h))), SizedBox(height: 10.v), Text("lbl_ngn20_000".tr, style: theme.textTheme.titleMedium), SizedBox(height: 3.v), Text("lbl_balance".tr, style: CustomTextStyles.titleSmallGray60001)]))])); } 
/// Section Widget
Widget _buildLoanHistory() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_loan_history".tr, style: CustomTextStyles.titleMediumMedium18), CustomImageView(imagePath: ImageConstant.imgIconsBlack900, height: 24.adaptSize, width: 24.adaptSize)])); } 
/// Section Widget
Widget _buildLoanDetails() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.loansModelObj.value.loandetails1ItemList.value.length, itemBuilder: (context, index) {Loandetails1ItemModel model = controller.loansModelObj.value.loandetails1ItemList.value[index]; return Loandetails1ItemWidget(model);}))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.borrowerHomeEmptyPage; case BottomBarEnum.Loans: return AppRoutes.loansEmptyPage; case BottomBarEnum.Notifications: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.borrowerHomeEmptyPage: return BorrowerHomeEmptyPage(); case AppRoutes.loansEmptyPage: return LoansEmptyPage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 

/// Displays a dialog with the [LoanlinkersPermissionDialog] content.
onTapRepayLoan() { Get.dialog(AlertDialog(backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0), content:LoanlinkersPermissionDialog(Get.put(LoanlinkersPermissionController(),),),)); } 
 }
