import '../lender_home_empty_screen/widgets/userprofile2_item_widget.dart';import 'controller/lender_home_empty_controller.dart';import 'models/userprofile2_item_model.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/presentation/borrower_home_empty_page/borrower_home_empty_page.dart';import 'package:loan_link/presentation/loans_empty_page/loans_empty_page.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:loan_link/widgets/app_bar/appbar_subtitle_two.dart';import 'package:loan_link/widgets/app_bar/appbar_trailing_image.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_bottom_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';class LenderHomeEmptyScreen extends GetWidget<LenderHomeEmptyController> {const LenderHomeEmptyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 72.v), _buildFundAccount1(), SizedBox(height: 32.v), _buildRecommendedFor(), SizedBox(height: 16.v), _buildUserProfile(), SizedBox(height: 30.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_recent_transactions".tr, style: CustomTextStyles.titleMediumMedium))), SizedBox(height: 43.v), CustomImageView(imagePath: ImageConstant.imgGroupBlueGray900, height: 79.v, width: 144.h), SizedBox(height: 12.v), Text("msg_no_transactions".tr, style: theme.textTheme.titleSmall), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse110324x24, margin: EdgeInsets.only(left: 20.h)), title: AppbarSubtitleTwo(text: "lbl_hi_samuel".tr, margin: EdgeInsets.only(left: 3.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconsBlueGray900, margin: EdgeInsets.symmetric(horizontal: 20.h))]); } 
/// Section Widget
Widget _buildFundAccount() { return CustomElevatedButton(height: 32.v, width: 122.h, text: "lbl_fund_account".tr, rightIcon: Container(margin: EdgeInsets.only(left: 3.h), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimarycontainer16x16, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillOnPrimary, buttonTextStyle: CustomTextStyles.labelLargePrimaryContainer, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildWithdraw() { return CustomElevatedButton(height: 32.v, width: 97.h, text: "lbl_withdraw".tr, rightIcon: Container(margin: EdgeInsets.only(left: 3.h), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimarycontainer16x16, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillOnPrimary, buttonTextStyle: CustomTextStyles.labelLargePrimaryContainer, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildFundAccount1() { return SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(left: 20.h), child: IntrinsicWidth(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [_buildFundAccount(), SizedBox(height: 2.v), _buildFrame(text: "lbl_wallet_balance".tr), SizedBox(height: 1.v), Text("lbl_ngn0_00".tr, style: CustomTextStyles.headlineSmallPrimaryContainer), SizedBox(height: 4.v)]))), Expanded(child: Container(margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100011.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [_buildWithdraw(), SizedBox(height: 2.v), _buildFrame(text: "lbl_wallet_balance".tr), SizedBox(height: 1.v), Text("lbl_ngn0_00".tr, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallPrimaryContainer), SizedBox(height: 4.v)])))]))); } 
/// Section Widget
Widget _buildRecommendedFor() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_recommended_for2".tr, style: CustomTextStyles.titleMediumMedium), GestureDetector(onTap: () {onTapTxtSeeMore();}, child: Text("lbl_see_more".tr, style: CustomTextStyles.titleSmallPrimary_1))])); } 
/// Section Widget
Widget _buildUserProfile() { return SizedBox(height: 317.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 20.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 11.h);}, itemCount: controller.lenderHomeEmptyModelObj.value.userprofile2ItemList.value.length, itemBuilder: (context, index) {Userprofile2ItemModel model = controller.lenderHomeEmptyModelObj.value.userprofile2ItemList.value[index]; return Userprofile2ItemWidget(model, onTapUserFundButton: () {onTapUserFundButton();});}))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildFrame({required String text}) { return Row(children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text(text, textAlign: TextAlign.center, style: CustomTextStyles.labelLargePrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer))), CustomImageView(imagePath: ImageConstant.imgIcons16x16, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.borrowerHomeEmptyPage; case BottomBarEnum.Loans: return AppRoutes.loansEmptyPage; case BottomBarEnum.Notifications: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.borrowerHomeEmptyPage: return BorrowerHomeEmptyPage(); case AppRoutes.loansEmptyPage: return LoansEmptyPage(); default: return DefaultWidget();} } 
/// Navigates to the loanDetailsScreen when the action is triggered.
onTapUserFundButton() { Get.toNamed(AppRoutes.loanDetailsScreen); } 
/// Navigates to the loanListingsScreen when the action is triggered.
onTapTxtSeeMore() { Get.toNamed(AppRoutes.loanListingsScreen, ); } 
 }
