import '../borrower_home_empty_page/widgets/totalloansframe_item_widget.dart';import 'controller/borrower_home_empty_controller.dart';import 'models/borrower_home_empty_model.dart';import 'models/totalloansframe_item_model.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:loan_link/widgets/app_bar/appbar_subtitle_two.dart';import 'package:loan_link/widgets/app_bar/appbar_trailing_image.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';import 'package:loan_link/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class BorrowerHomeEmptyPage extends StatelessWidget {BorrowerHomeEmptyPage({Key? key}) : super(key: key);

BorrowerHomeEmptyController controller = Get.put(BorrowerHomeEmptyController(BorrowerHomeEmptyModel().obs));

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 72.v), CustomElevatedButton(height: 18.v, width: 160.h, text: "msg_loan_limit_n50_000".tr, margin: EdgeInsets.only(left: 20.h), rightIcon: Container(margin: EdgeInsets.only(left: 4.h), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleSmallBold, onPressed: () {onTapLoanLimitN50000();}, alignment: Alignment.centerLeft), SizedBox(height: 9.v), _buildTotalLoansFrame(), SizedBox(height: 32.v), _buildView(), SizedBox(height: 42.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_complete_your_account".tr, style: CustomTextStyles.titleMediumMedium))), SizedBox(height: 17.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: CustomTextFormField(controller: controller.iconsController, hintText: "msg_add_your_bvn_or".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 16.v, 7.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary24x24, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(top: 18.v, right: 30.h, bottom: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL8)), SizedBox(height: 41.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_quick_actions".tr, style: CustomTextStyles.titleMediumMedium))), SizedBox(height: 18.v), _buildIcons3(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse1103, margin: EdgeInsets.only(left: 20.h)), title: AppbarSubtitleTwo(text: "lbl_hi_mcclive".tr, margin: EdgeInsets.only(left: 3.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconsBlueGray900, margin: EdgeInsets.symmetric(horizontal: 20.h))]); } 
/// Section Widget
Widget _buildTotalLoansFrame() { return SizedBox(height: 86.v, child: Obx(() => ListView.separated(padding: EdgeInsets.symmetric(horizontal: 20.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.borrowerHomeEmptyModelObj.value.totalloansframeItemList.value.length, itemBuilder: (context, index) {TotalloansframeItemModel model = controller.borrowerHomeEmptyModelObj.value.totalloansframeItemList.value[index]; return TotalloansframeItemWidget(model);}))); } 
/// Section Widget
Widget _buildView() { return Container(height: 188.v, width: 390.h, decoration: AppDecoration.outlineBlack900, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(height: 88.v, width: 390.h, decoration: BoxDecoration(borderRadius: BorderRadius.vertical(top: Radius.circular(12.h)), gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [theme.colorScheme.secondaryContainer, theme.colorScheme.errorContainer])))), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 108.h, vertical: 39.v), decoration: AppDecoration.fillErrorContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_no_transactions".tr, style: CustomTextStyles.titleSmallPrimaryContainer)]))), CustomImageView(imagePath: ImageConstant.imgGroupBlueGray900, height: 79.v, width: 144.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 36.v))])); } 
/// Section Widget
Widget _buildIcons3() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 12.h), child: _buildIcons(userImage: ImageConstant.imgIconsPrimary32x32, labelText: "lbl_apply_for_loan".tr, onTapIcons: () {onTapIcons();})), Padding(padding: EdgeInsets.only(left: 12.h), child: _buildIcons(userImage: ImageConstant.imgIcons, labelText: "lbl_make_repayment".tr))])); } 
/// Common widget
Widget _buildIcons({required String userImage, required String labelText, Function? onTapIcons, }) { return GestureDetector(onTap: () {onTapIcons!.call();}, child: Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 15.v), decoration: AppDecoration.outlineAmber.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: userImage, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 9.v), Text(labelText, style: CustomTextStyles.titleSmallLime900.copyWith(color: appTheme.lime900))]))))); } 
/// Navigates to the loanLimitInfoScreen when the action is triggered.
onTapLoanLimitN50000() { Get.toNamed(AppRoutes.loanLimitInfoScreen, ); } 
/// Navigates to the loanRequestOneScreen when the action is triggered.
onTapIcons() { Get.toNamed(AppRoutes.loanRequestOneScreen, ); } 
 }
