import 'controller/loan_request_one_controller.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/widgets/app_bar/appbar_leading_image.dart';import 'package:loan_link/widgets/app_bar/appbar_subtitle_one.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_drop_down.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';import 'package:loan_link/widgets/custom_outlined_button.dart';import 'package:loan_link/widgets/custom_text_form_field.dart';class LoanRequestOneScreen extends GetWidget<LoanRequestOneController> {const LoanRequestOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), SizedBox(height: 72.v), _buildSTEP10F2(), SizedBox(height: 18.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_loan_information".tr, style: CustomTextStyles.titleMediumMedium18))), SizedBox(height: 26.v), _buildFrame(), SizedBox(height: 25.v), _buildFrame1(), SizedBox(height: 24.v), _buildFrame2(), SizedBox(height: 25.v), _buildFrame3(), SizedBox(height: 23.v), _buildInput(), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Column(children: [Text("lbl_interest".tr, style: theme.textTheme.titleSmall), SizedBox(height: 19.v), Text("lbl_0_00_0".tr, style: CustomTextStyles.titleMediumBold)]))), SizedBox(height: 39.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_total_amount_to".tr, style: theme.textTheme.titleSmall), SizedBox(height: 18.v), Text("lbl_0_00".tr, style: CustomTextStyles.titleMediumBold)]))), SizedBox(height: 55.v), _buildProceed(), SizedBox(height: 55.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleOne(text: "lbl_request_loan".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSTEP10F2() { return CustomElevatedButton(height: 24.v, width: 85.h, text: "lbl_step_1_0f_2".tr, margin: EdgeInsets.only(left: 20.h), buttonStyle: CustomButtonStyles.fillDeepPurple, buttonTextStyle: CustomTextStyles.labelLargeBluegray900, alignment: Alignment.centerLeft); } 
/// Section Widget
Widget _buildAmount() { return CustomTextFormField(controller: controller.amountController, hintText: "lbl_enter_amount".tr); } 
/// Section Widget
Widget _buildFrame() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_loan_amount".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), _buildAmount()])); } 
/// Section Widget
Widget _buildPhoneNumber() { return CustomTextFormField(controller: controller.phoneNumberController, hintText: "msg_enter_purpose_description".tr); } 
/// Section Widget
Widget _buildFrame1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_purpose_of_loan".tr, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), _buildPhoneNumber(), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Text("lbl_0_200_words".tr, style: CustomTextStyles.bodySmallGothicA1Gray70012))])); } 
/// Section Widget
Widget _buildFrame2() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_loan_term".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_term".tr, items: controller.loanRequestOneModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildSelectDay() { return CustomTextFormField(controller: controller.selectDayController, hintText: "lbl_select_day".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 8.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgIconsGray600, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 8.h, top: 15.v, bottom: 15.v)); } 
/// Section Widget
Widget _buildFrame3() { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_repayment_day".tr, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), _buildSelectDay(), SizedBox(height: 5.v), Text("msg_please_choose_the".tr, style: CustomTextStyles.bodySmallGothicA1DeeppurpleA700)])); } 
/// Section Widget
Widget _buildUploadFile() { return CustomOutlinedButton(height: 40.v, width: 100.h, text: "lbl_upload_file".tr, buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleSmallPrimary_1); } 
/// Section Widget
Widget _buildInput() { return Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_cover_picture".tr, style: CustomTextStyles.titleSmallGray90001), SizedBox(height: 6.v), Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 7.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [_buildUploadFile(), Padding(padding: EdgeInsets.only(left: 25.h, top: 11.v, bottom: 10.v), child: Text("msg_no_file_uploaded".tr, style: CustomTextStyles.bodyMediumGray600))])), SizedBox(height: 8.v), Text("msg_accepted_formats".tr, style: CustomTextStyles.bodySmallGothicA1)])); } 
/// Section Widget
Widget _buildProceed() { return CustomElevatedButton(text: "lbl_proceed".tr, margin: EdgeInsets.symmetric(horizontal: 20.h), onPressed: () {onTapProceed();}); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the loanRequestTwoTabContainerScreen when the action is triggered.
onTapProceed() { Get.toNamed(AppRoutes.loanRequestTwoTabContainerScreen, ); } 
 }
