import 'controller/otp_controller.dart';import 'package:flutter/material.dart';import 'package:loan_link/core/app_export.dart';import 'package:loan_link/widgets/app_bar/appbar_title.dart';import 'package:loan_link/widgets/app_bar/custom_app_bar.dart';import 'package:loan_link/widgets/custom_elevated_button.dart';import 'package:loan_link/widgets/custom_pin_code_text_field.dart';import 'package:loan_link/presentation/otp_success_dialog/otp_success_dialog.dart';import 'package:loan_link/presentation/otp_success_dialog/controller/otp_success_controller.dart';class OtpScreen extends GetWidget<OtpController> {const OtpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 47.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer)), Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 50.v), child: Column(children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.onErrorContainer, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder74), child: Container(height: 148.adaptSize, width: 148.adaptSize, padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 5.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder74), child: Stack(alignment: Alignment.centerRight, children: [CustomImageView(imagePath: ImageConstant.imgTwemojiMobile, height: 109.v, width: 67.h, alignment: Alignment.bottomCenter), CustomImageView(imagePath: ImageConstant.imgIconsPrimarycontainer, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.centerRight)]))), SizedBox(height: 33.v), Container(width: 344.h, margin: EdgeInsets.only(left: 23.h, right: 22.h), child: Text("msg_please_enter_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumBluegray900.copyWith(height: 1.43))), SizedBox(height: 48.v), Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {})), SizedBox(height: 68.v), CustomElevatedButton(text: "lbl_proceed".tr, onPressed: () {onTapProceed();}), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 4.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_didn_t_receive_otp2".tr, style: CustomTextStyles.bodyLargeGray800_1), TextSpan(text: "lbl2".tr, style: CustomTextStyles.bodyLargeGray800_1), TextSpan(text: "lbl_resend_otp".tr, style: CustomTextStyles.titleMediumPrimary)]), textAlign: TextAlign.left))), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 54.v, title: AppbarTitle(text: "msg_otp_verification".tr, margin: EdgeInsets.only(left: 20.h))); } 

/// Displays a dialog with the [OtpSuccessDialog] content.
onTapProceed() { Get.dialog(AlertDialog(backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0), content:OtpSuccessDialog(Get.put(OtpSuccessController(),),),)); } 
 }
